services:
  litellm:
    image: docker.litellm.ai/berriai/litellm-database:latest

    ports:
      - "4000:4000"

    environment:
      LITELLM_MASTER_KEY: sk-1234
      LITELLM_SALT_KEY: sk-XXXXXXXXXXXXXXXX
      DATABASE_URL: postgresql://litellm:litellm@db:5432/litellm
      STORE_MODEL_IN_DB: "True"
      OLLAMA_HOST: http://host.docker.internal:11434

      PRESIDIO_ANALYZER_API_BASE: http://presidio-analyzer:3000
      PRESIDIO_ANONYMIZER_API_BASE: http://presidio-anonymizer:3000

    volumes:
      - ./config.yaml:/app/config.yaml

    command:
      - "--config=/app/config.yaml"
      - "--port=4000"

    depends_on:
      db:
        condition: service_healthy
      presidio-analyzer:
        condition: service_started
      presidio-anonymizer:
        condition: service_started

  presidio-analyzer:
    image: mcr.microsoft.com/presidio-analyzer:latest
    ports:
      - "3000:3000"

  presidio-anonymizer:
    image: mcr.microsoft.com/presidio-anonymizer:latest
    ports:
      - "3001:3000"


  db:
    image: postgres:16

    environment:
      POSTGRES_USER: litellm
      POSTGRES_PASSWORD: litellm
      POSTGRES_DB: litellm

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U litellm"]
      interval: 5s
      timeout: 5s
      retries: 10

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
